# Generated by Django 4.0.4 on 2022-05-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="urlshorten",
            name="analytics_id",
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
